server:
  port : 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/password_management
    username: postgres
    password: 123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false



#logging:
  #level:
    #org.apache.http: DEBUG
    #org.springframework.orm.jpa: DEBUG 
    #org.springframework.transaction: DEBUG 
    #org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    #org.hibernate.SQL: DEBUG